### ISSUE TITLE
Tuning dataset for Llama Reflection 70B

### ISSUE THREAD

**Issue by nmathewa** [Numetria/NuCast#2]
# ToDo

- [x] Download the local version of the model
- [ ] Test the model for a simple case and complex case 
- [ ] Create a custom/sample dataset for tuning 
- [ ] Tune the model successfully and evaluate the results
